import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

let toto : string = "toto";
// ici on déclare une variable de type string
// en typescript on déclare une variable avec le type de la variable après le nom de la variable

let tonton = (neveu: number) => {}
// ici on déclare une fonction qui prend un paramètre de type number et qui ne retourne rien

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
